# Generated by Django 6.0.4 on 2026-04-11 20:40

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('contact', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True, default='')),
                ('entries', models.JSONField(blank=True, default=operations.models.list_default)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinishedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(default='Completed', max_length=40)),
                ('products', models.JSONField(blank=True, default=operations.models.list_default)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GateOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=160)),
                ('customer_name', models.CharField(blank=True, default='', max_length=160)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=80)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(default='Dispatched', max_length=40)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=120)),
                ('product', models.CharField(max_length=160)),
                ('outgoing', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='Unit', max_length=40)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('product', models.CharField(max_length=160)),
                ('subcategory', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('brand', 'category', 'product'),
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('items', models.JSONField(blank=True, default=operations.models.list_default)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('for_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('for_unit', models.CharField(default='Kg', max_length=40)),
                ('status', models.BooleanField(default=True)),
                ('items', models.JSONField(blank=True, default=operations.models.list_default)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_name', models.CharField(max_length=160)),
                ('entry_by', models.CharField(blank=True, default='', max_length=160)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('comment', models.TextField(blank=True, default='')),
                ('items', models.JSONField(blank=True, default=operations.models.list_default)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.TextField(blank=True, default='')),
                ('contact', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='operations.brand')),
            ],
            options={
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='operations.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='operations.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='GateInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gr_no', models.CharField(max_length=40, unique=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=160)),
                ('address', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('receive_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], default='Received', max_length=20)),
                ('items', models.JSONField(blank=True, default=operations.models.list_default)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_inwards', to='operations.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='operations.product')),
            ],
            options={
                'unique_together': {('name', 'product')},
            },
        ),
    ]
