# Generated by Django 6.0.4 on 2026-04-12 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='produced_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='operations.productionorder'),
        ),
        migrations.AddField(
            model_name='finishedgoods',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.product'),
        ),
        migrations.AddField(
            model_name='finishedgoods',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='finishedgoods',
            name='unit',
            field=models.CharField(default='Unit', max_length=40),
        ),
        migrations.AddField(
            model_name='gateoutward',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.customer'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.product'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='unit',
            field=models.CharField(default='Unit', max_length=40),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='operations.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='finishedgoods',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='gateinward',
            name='gr_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gateinward',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='gateoutward',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='gateoutward',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='product',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='entry_by',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='receiver_name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.CreateModel(
            name='GateInwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gate_inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_inward_items', to='operations.gateinward')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GateOutwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('gate_outward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_outward_items', to='operations.gateoutward')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='operations.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJUST', 'ADJUST')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('remarks', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(default='Kg', max_length=40)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='operations.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='operations.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_items', to='operations.requisition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
