# Generated by Django 6.0.4 on 2026-04-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='operations.product'),
        ),
        migrations.AddField(
            model_name='size',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]

